export const meetup = {
  id: 6,
  title: 'VueConf US',
  description: 'ATX. Code. Vue.\nhttps://vueconf.us/',
  imageId: 5,
  date: 1589241600000,
  organizer: 'Evan You',
  place: 'USA, AUSTIN CONVENTION CENTER',
  agenda: [
    {
      id: 35,
      startsAt: '07:30',
      endsAt: '09:00',
      type: 'registration',
      title: null,
      description: null,
      speaker: null,
      language: null,
    },
    {
      id: 36,
      startsAt: '09:00',
      endsAt: '09:30',
      type: 'opening',
      title: 'Opening Keynote with Evan',
      description: null,
      speaker: null,
      language: null,
    },
    {
      id: 37,
      startsAt: '09:40',
      endsAt: '10:10',
      type: 'talk',
      title: 'Get the most out of Vue Router',
      description:
        "Routers in Single page applications touch a broad part of our business logic. As a consequence, we often end up with different ways of handling the same pattern/UX/logic in our code and we often wonder which one is better and why. Different ways of handling data fetching that change the user experience, different ways to implement layouts, and many more. During this talk, I will cover very practical implementations that I have found useful in the past and explain the differences between various Vue Router features. After the talk you will have a better understanding of Vue Router's API and hopefully the excitement to refactor some bits of your Vue app!",
      speaker: 'Eduardo',
      language: 'EN',
    },
    {
      id: 38,
      startsAt: '10:10',
      endsAt: '09:30',
      type: 'break',
      title: 'Break 1.0',
      description: null,
      speaker: null,
      language: null,
    },
    {
      id: 39,
      startsAt: '10:40',
      endsAt: '11:10',
      type: 'talk',
      title: 'All you need is <s>love</s> Apollo Client',
      description:
        'While we usually mention Apollo Client only in connection with GraphQL, it can do a lot more things to your Vue application such as accessing REST endpoints and replacing Vuex in managing application state! In this talk, I will cover these advanced cases while also explaining the basics of using Apollo with GraphQL endpoints',
      speaker: 'Natalia Tepluhina',
      language: 'EN',
    },
    {
      id: 40,
      startsAt: '11:10',
      endsAt: '11:40',
      type: 'talk',
      title: 'The State of CSS in Vue',
      description:
        "There are a lot of ways to include CSS in your Vue apps, and they all have pros and cons. Knowing which method to choose can be confusing with all the different options available. In this talk, you'll learn about different ways to bring CSS into your Vue app and how to pick a methodology for your project.",
      speaker: 'Jamena McInteer',
      language: 'EN',
    },
    {
      id: 41,
      startsAt: '11:40',
      endsAt: '12:10',
      type: 'talk',
      title: "What you'll love in Vue 3",
      description: "What you'll love in Vue 3",
      speaker: 'Alex Kyriakidis',
      language: 'EN',
    },
    {
      id: 42,
      startsAt: '12:10',
      endsAt: '13:10',
      type: 'coffee',
      title: 'Lunch 1.0',
      description: null,
      speaker: null,
      language: null,
    },
    {
      id: 43,
      startsAt: '13:10',
      endsAt: '14:10',
      type: 'other',
      title: 'Lightning Talks 1.0',
      description: null,
      speaker: null,
      language: null,
    },
    {
      id: 44,
      startsAt: '14:10',
      endsAt: '14:40',
      type: 'break',
      title: 'Break 1.1',
      description: null,
      speaker: null,
      language: null,
    },
    {
      id: 45,
      startsAt: '14:40',
      endsAt: '15:10',
      type: 'talk',
      title: 'Vuetify v2+',
      description:
        'A review of the past year of Vuetify, the v2 releases and upcoming features in v2.2. Details of new packages for the Vuetify ecosystem and future projects on the horizon.',
      speaker: 'John Leider',
      language: 'EN',
    },
    {
      id: 46,
      startsAt: '15:10',
      endsAt: '15:40',
      type: 'talk',
      title: "Content Loading That Isn't Broken",
      description:
        "How does Vue.js handle rerouting and loading new content with a screen reader? Let's explore how we can improve the experience for a lot of users who rely on assistive technologies.",
      speaker: 'Maria Lamardo',
      language: 'EN',
    },
    {
      id: 47,
      startsAt: '15:40',
      endsAt: '16:10',
      type: 'talk',
      title: 'Documenting components made easy',
      description:
        "Using shared components without proper documentation can be a pain. Whether you're publishing a component library, or just sharing components with your colleagues, increase the ease of adoption by writing clear documentation. In this talk, I'll show you how easy it is to write beautiful documentation for your components which other developers will love.",
      speaker: 'Bart Ledoux',
      language: 'EN',
    },
    {
      id: 48,
      startsAt: '16:10',
      endsAt: '16:40',
      type: 'break',
      title: 'Break 1.3',
      description: null,
      speaker: null,
      language: null,
    },
    {
      id: 49,
      startsAt: '16:40',
      endsAt: '17:10',
      type: 'talk',
      title: 'TypeScript & Vue @ Politico',
      description:
        '“JavaScript that scales” is the tagline for TypeScript, and it can be a beautiful partner for increasingly complex Vue apps. We’ll discuss how CLI TypeScript Vue projects can increase development speed, decrease onboarding time, type errors, and typos, while encouraging self-documenting & maintainable code. Finally, let’s look at remaining hurdles for Vue’s TS implementation (Vuex, mixins, templates), and how the composition API + Vetur will continue to ease those growing pains.',
      speaker: 'Jack Koppa',
      language: 'EN',
    },
    {
      id: 50,
      startsAt: '17:10',
      endsAt: '17:40',
      type: 'talk',
      title: 'Unconventional Vue—Vue as a Backend Framework',
      description:
        'While Vue has emerged as a dominant frontend framework, we can’t forget about the other side of the spectrum. What if we leveraged Vue 3.0’s powerful standalone observability system to manage our backend datastore, with all its reactivity goodness? We could build a highly reactive chat app, power a live scoreboard, or maybe even have Vue trigger AWS Lambda functions as app data changes…',
      speaker: 'Oscar Spencer',
      language: 'EN',
    },
    {
      id: 51,
      startsAt: '18:15',
      endsAt: '19:45',
      type: 'afterparty',
      title:
        'Conference Reception: Austin SPEAKEASY, 412 Congress Ave. Drinks and light snacks.',
      description: null,
      speaker: null,
      language: null,
    },
  ],
};
